name: LottoAI
options:
  bundleIdPrefix: com.ericcirex
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    SWIFT_VERSION: "5.9"
    ENABLE_PREVIEWS: YES

targets:
  LottoAI:
    type: application
    platform: iOS
    sources:
      - LottoAI
    settings:
      base:
        INFOPLIST_FILE: LottoAI/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.ericcirex.lottoai
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_ENTITLEMENTS: LottoAI/Resources/LottoAI.entitlements
    info:
      path: LottoAI/Resources/Info.plist
      properties:
        CFBundleDisplayName: Lotto AI
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        UILaunchScreen:
          UIColorName: AccentColor
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIUserInterfaceStyle: Dark
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: false
          NSExceptionDomains:
            ericcirex.github.io:
              NSExceptionAllowsInsecureHTTPLoads: false
              NSIncludesSubdomains: true
        UIBackgroundModes:
          - remote-notification
    dependencies:
      - target: LottoAIWidgetExtension

  LottoAIWidgetExtension:
    type: app-extension
    platform: iOS
    sources:
      - LottoAIWidget
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ericcirex.lottoai.widget
        INFOPLIST_FILE: LottoAIWidget/Info.plist
        ASSETCATALOG_COMPILER_WIDGET_BACKGROUND_COLOR_NAME: WidgetBackground
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_ENTITLEMENTS: LottoAIWidget/LottoAIWidget.entitlements
    info:
      path: LottoAIWidget/Info.plist
      properties:
        CFBundleDisplayName: Lotto AI Widget
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
